import pc from "picocolors";

import { CATEGORY_LABELS, PRIORITIES } from "../generator/schema.js";
import { percent } from "./coverage.js";

const SEVERITY_LABEL = { high: "High", medium: "Medium", low: "Low" };
const SEVERITY_COLOR = { high: pc.red, medium: pc.yellow, low: pc.dim };
const STATUS_MARK = { passed: "PASS", failed: "FAIL", skipped: "SKIP", unknown: "?" };

/** Markdown report, for committing to a repo or pasting into a PR. */
export function renderMarkdown(report) {
  const lines = [
    "# Test coverage report",
    "",
    `_${report.sourceSummary}_`,
    "",
    "| | |",
    "|---|---|",
    `| Source | ${report.sourceType === "openapi" ? "OpenAPI specification" : "user story"} |`,
    `| Generated | ${report.generatedAt} |`,
    `| Test cases | ${report.totals.cases} |`,
    `| Automated | ${report.totals.automated} of ${report.totals.cases} (${percent(report.totals.automated, report.totals.cases)}%) |`,
    `| Steps translated | ${report.totals.translatedSteps} of ${report.totals.steps} (${percent(report.totals.translatedSteps, report.totals.steps)}%) |`,
    `| Assertions | ${report.totals.assertions} |`,
  ];

  if (report.hasResults) {
    const { passed, failed, skipped } = report.results;
    lines.push(`| Last run | ${passed} passed, ${failed} failed, ${skipped} skipped |`);
  }
  lines.push("");

  if (report.gaps.length > 0) {
    lines.push("## Gaps to review", "");
    for (const gap of report.gaps) {
      lines.push(`- **${SEVERITY_LABEL[gap.severity]}** — ${gap.message}`);
      lines.push(`  ${gap.detail}`);
    }
    lines.push("");
  } else {
    lines.push("## Gaps to review", "", "Nothing flagged.", "");
  }

  lines.push("## Coverage by category", "", "| Category | Cases | Automated |", "|---|---|---|");
  for (const entry of report.byCategory) {
    const count = entry.count === 0 ? "**0**" : String(entry.count);
    lines.push(`| ${entry.label} | ${count} | ${entry.automated} |`);
  }
  lines.push("");

  lines.push("## Coverage by priority", "", "| Priority | Cases |", "|---|---|");
  for (const priority of PRIORITIES) {
    lines.push(`| ${priority} | ${report.byPriority[priority]} |`);
  }
  lines.push("");

  lines.push("## Cases", "");
  for (const entry of report.byCategory) {
    const cases = report.cases.filter((c) => c.category === entry.category);
    if (cases.length === 0) continue;

    lines.push(`### ${entry.label}`, "");
    for (const testCase of cases) {
      const marks = [testCase.priority];
      marks.push(testCase.automated ? "automated" : "needs work");
      if (testCase.status) marks.push(`last run: ${testCase.status}`);

      lines.push(`#### ${testCase.id} · ${testCase.title}`, "");
      lines.push(`\`${marks.join("\` · \`")}\``, "");
      if (testCase.rationale) lines.push(`**Why it matters:** ${testCase.rationale}`, "");
      if (testCase.unresolved.length > 0) {
        lines.push("Blocking automation:", "");
        for (const item of testCase.unresolved) lines.push(`- ${item}`);
        lines.push("");
      }
    }
  }

  lines.push("---", "", "Generated by [ai-test-generator](https://github.com/afrahossain02/ai-test-generator).");
  return `${lines.join("\n")}\n`;
}

/** Compact terminal summary — the same findings, sized for a shell. */
export function renderTerminal(report) {
  const lines = ["", pc.bold("Coverage report"), pc.dim(report.sourceSummary), ""];

  const automatedPercent = percent(report.totals.automated, report.totals.cases);
  lines.push(
    `  ${pc.bold(String(report.totals.cases))} cases · ` +
      `${pc.bold(String(report.totals.automated))} automated (${automatedPercent}%) · ` +
      `${report.totals.assertions} assertions`,
  );

  if (report.hasResults) {
    const { passed, failed, skipped } = report.results;
    lines.push(
      `  Last run: ${pc.green(`${passed} passed`)} · ` +
        `${failed > 0 ? pc.red(`${failed} failed`) : "0 failed"} · ${pc.dim(`${skipped} skipped`)}`,
    );
  }
  lines.push("");

  lines.push(
    "  " +
      report.byCategory
        .map((entry) => {
          const text = `${CATEGORY_LABELS[entry.category]}: ${entry.count}`;
          return entry.count === 0 ? pc.red(text) : text;
        })
        .join(pc.dim("  |  ")),
  );
  lines.push("");

  if (report.gaps.length === 0) {
    lines.push(`  ${pc.green("✓")} Nothing flagged.`, "");
  } else {
    lines.push(pc.bold("  Gaps to review"), "");
    for (const gap of report.gaps) {
      const color = SEVERITY_COLOR[gap.severity];
      lines.push(`  ${color(`[${SEVERITY_LABEL[gap.severity]}]`)} ${gap.message}`);
      lines.push(pc.dim(`        ${gap.detail}`));
    }
    lines.push("");
  }

  const failed = report.cases.filter((entry) => entry.status === "failed");
  if (failed.length > 0) {
    lines.push(pc.bold("  Failing cases"), "");
    for (const entry of failed) {
      lines.push(`  ${pc.red(STATUS_MARK.failed)} ${entry.id} · ${entry.title}`);
      lines.push(pc.dim(`        Why it matters: ${entry.rationale}`));
    }
    lines.push("");
  }

  return lines.join("\n");
}
