import { z } from "zod";

import { TestStepSchema } from "./schema.js";
import { translateAction, translateObservation, quote } from "./stepTranslator.js";
import { uiPreamble } from "./codeGenerator.js";
import { GenerationError } from "../utils/errors.js";

/**
 * An authentication profile: the steps that sign a user in, once.
 *
 * Written in the same sentence shapes as a test case, because signing in is
 * just a sequence of UI steps — there is no reason for it to have a second
 * grammar, and reusing the translator means the same locator map applies.
 */
export const AuthProfileSchema = z.object({
  name: z.string().min(1),
  url: z.string().min(1),
  steps: z.array(TestStepSchema).min(1),
  expectedResult: z.string(),
});

export const DEFAULT_AUTH_STATE_PATH = ".auth/user.json";

export function parseAuthProfile(value, { filename = "auth profile" } = {}) {
  const result = AuthProfileSchema.safeParse(value);
  if (!result.success) {
    throw new GenerationError(`${filename} is not a valid auth profile.`, {
      hint: 'Expected { "name": "...", "url": "/login", "steps": [...], "expectedResult": "..." }.',
    });
  }
  return result.data;
}

/**
 * Renders the Playwright setup project that signs in and saves storage state.
 *
 * Every step must translate. A test case with one unreadable step is still
 * useful — it runs as far as it can and is flagged. A sign-in with one
 * unreadable step authenticates nobody, and would hand every dependent test a
 * cookie jar that is silently empty, so this refuses instead.
 */
export function generateAuthSetup(profile, { locators = null, statePath = DEFAULT_AUTH_STATE_PATH } = {}) {
  const lines = [];
  const unresolved = [];

  lines.push(`    await page.goto(${quote(profile.url)});`);
  lines.push("");

  profile.steps.forEach((step, index) => {
    lines.push(`    // ${index + 1}. ${step.action}`);

    const action = translateAction(step.action, "ui");
    if (action.resolved) {
      lines.push(...action.statements.map((statement) => `    ${statement}`));
    } else {
      unresolved.push(`step ${index + 1}: ${step.action}`);
    }

    const observation = translateObservation(step.expectedObservation, "ui");
    lines.push(...observation.statements.map((statement) => `    ${statement}`));
    lines.push("");
  });

  const outcome = translateObservation(profile.expectedResult, "ui");
  if (outcome.statements.length === 0) {
    unresolved.push(`expected result: ${profile.expectedResult}`);
  } else {
    lines.push(`    // Confirm the sign-in actually worked before saving the session.`);
    lines.push(...outcome.statements.map((statement) => `    ${statement}`));
    lines.push("");
  }

  if (unresolved.length > 0) {
    throw new GenerationError(
      `The auth profile "${profile.name}" has steps that cannot be compiled.`,
      {
        hint: `Rephrase these in shapes the translator understands:\n    - ${unresolved.join("\n    - ")}`,
      },
    );
  }

  const header = [
    "// Generated by ai-test-generator. Regenerating overwrites this file.",
    "//",
    `// Signs in as: ${profile.name}`,
    "//",
    "// Runs once as a Playwright setup project. The tests that depend on it",
    "// start already authenticated, instead of signing in again per test.",
  ].join("\n");

  const body = [
    `const AUTH_STATE = ${quote(statePath)};`,
    "",
    `setup(${quote(`authenticate as ${profile.name}`)}, async ({ page }) => {`,
    ...lines,
    "    await page.context().storageState({ path: AUTH_STATE });",
    "});",
  ].join("\n");

  const preamble = uiPreamble(locators).replace(
    "import { test, expect } from '@playwright/test';",
    "import { test as setup, expect } from '@playwright/test';",
  );

  return `${header}\n${preamble}\n${body}\n`;
}
