import { CATEGORIES } from "./schema.js";
import { translateAction, translateObservation, quote } from "./stepTranslator.js";

const CATEGORY_TITLES = {
  happy_path: "Happy path",
  edge_case: "Edge cases",
  negative: "Negative",
  boundary: "Boundary",
  security: "Security",
};

const INDENT = "  ";

/**
 * Turns a validated TestPlan into the source of a Playwright spec file.
 *
 * Pure: takes a plan, returns a string and a set of counts. No filesystem, no
 * network, so the interesting logic is testable without touching either.
 *
 * @param {object} plan - a plan that has been through parseTestPlan()
 * @returns {{source: string, stats: object}}
 */
export function generateSpec(plan) {
  const stats = {
    tests: 0,
    runnable: 0,
    fixme: 0,
    steps: 0,
    translatedSteps: 0,
    assertions: 0,
  };

  const blocks = [];
  for (const category of CATEGORIES) {
    const cases = plan.testCases.filter((testCase) => testCase.category === category);
    if (cases.length === 0) continue;

    const body = cases.map((testCase) => renderTestCase(testCase, stats)).join("\n\n");
    blocks.push(`test.describe(${quote(CATEGORY_TITLES[category])}, () => {\n${body}\n});`);
  }

  const source = [header(plan), PREAMBLE, blocks.join("\n\n"), ""].join("\n");
  return { source, stats };
}

function header(plan) {
  return [
    "// Generated by ai-test-generator. Regenerating overwrites this file.",
    "//",
    `// Source: ${plan.sourceSummary}`,
    `// Generated: ${plan.generatedAt}`,
    "//",
    "// Tests marked test.fixme have steps the generator could not translate into",
    "// Playwright calls. They are skipped rather than passed — fill in the TODOs",
    "// and change fixme to test to bring them into the suite.",
  ].join("\n");
}

const PREAMBLE = `
import { test, expect } from '@playwright/test';

/** Matches a form control by its visible label, falling back to placeholder text. */
const field = (page, name) =>
  page.getByLabel(name).or(page.getByPlaceholder(name)).first();

/** Matches a button or link by its accessible name. */
const clickable = (page, name) =>
  page.getByRole('button', { name }).or(page.getByRole('link', { name })).first();
`;

function renderTestCase(testCase, stats) {
  const lines = [];
  const unresolved = [];
  let assertions = 0;

  for (const precondition of testCase.preconditions) {
    lines.push(`${INDENT.repeat(2)}// Given: ${precondition}`);
  }
  if (testCase.preconditions.length > 0) lines.push("");

  testCase.steps.forEach((step, index) => {
    stats.steps += 1;
    lines.push(`${INDENT.repeat(2)}// ${index + 1}. ${step.action}`);

    const action = translateAction(step.action);
    if (action.resolved) {
      stats.translatedSteps += 1;
      lines.push(...indent(action.statements, 2));
    } else {
      unresolved.push(`step ${index + 1}: ${step.action}`);
      lines.push(`${INDENT.repeat(2)}// TODO: translate this step`);
    }

    const observation = translateObservation(step.expectedObservation);
    if (observation.statements.length > 0) {
      assertions += observation.statements.length;
      lines.push(...indent(observation.statements, 2));
    } else if (!observation.resolved) {
      unresolved.push(`assertion for step ${index + 1}: ${step.expectedObservation}`);
      lines.push(`${INDENT.repeat(2)}// TODO: assert — ${step.expectedObservation}`);
    }

    lines.push("");
  });

  lines.push(`${INDENT.repeat(2)}// Expect: ${testCase.expectedResult}`);
  const outcome = translateObservation(testCase.expectedResult);
  if (outcome.statements.length > 0) {
    assertions += outcome.statements.length;
    lines.push(...indent(outcome.statements, 2));
  } else {
    unresolved.push(`final assertion: ${testCase.expectedResult}`);
    lines.push(`${INDENT.repeat(2)}// TODO: assert the expected result`);
  }

  // A test that asserts nothing passes by doing nothing, which is worse than a
  // test that is openly unfinished. Never emit one as runnable.
  const needsWork = unresolved.length > 0 || assertions === 0;

  stats.tests += 1;
  stats.assertions += assertions;
  if (needsWork) stats.fixme += 1;
  else stats.runnable += 1;

  const title = `${testCase.id} · ${testCase.title}`;
  const opener = needsWork ? "test.fixme" : "test";
  const notes = needsWork ? renderNotes(unresolved, assertions) : [];

  return [
    ...notes,
    `${INDENT}${opener}(${quote(title)}, async ({ page }) => {`,
    ...lines,
    `${INDENT}});`,
  ].join("\n");
}

function renderNotes(unresolved, assertions) {
  const notes = [`${INDENT}// Needs attention before this test can run:`];
  for (const item of unresolved) {
    notes.push(`${INDENT}//   - ${item}`);
  }
  if (assertions === 0) {
    notes.push(`${INDENT}//   - nothing in this case could be turned into an assertion`);
  }
  return notes;
}

function indent(statements, depth) {
  return statements.map((statement) => `${INDENT.repeat(depth)}${statement}`);
}

/** Filename-safe slug derived from a plan's summary. */
export function slugify(value, fallback = "test-plan") {
  const slug = String(value)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .split("-")
    .slice(0, 6)
    .join("-");
  return slug || fallback;
}

/** One-line summary of a codegen run, for the CLI to print. */
export function summarizeStats(stats) {
  const stepPercent =
    stats.steps === 0 ? 0 : Math.round((stats.translatedSteps / stats.steps) * 100);
  return (
    `${stats.tests} tests · ${stats.runnable} runnable · ${stats.fixme} need work · ` +
    `${stats.translatedSteps}/${stats.steps} steps translated (${stepPercent}%) · ` +
    `${stats.assertions} assertions`
  );
}
