import { CATEGORIES, CATEGORY_LABELS } from "./schema.js";
import { DEFAULT_TEST_ID_ATTRIBUTE } from "./locatorMap.js";
import { translateAction, translateObservation, quote } from "./stepTranslator.js";

/** Which translation rules and Playwright fixture a plan compiles against. */
export function specMode(plan) {
  return plan.sourceType === "openapi" ? "api" : "ui";
}

/** Spec files are named by mode so playwright.config can give each its own baseURL. */
export function specSuffix(plan) {
  return specMode(plan) === "api" ? ".api.spec.js" : ".ui.spec.js";
}

const INDENT = "  ";

/**
 * Turns a validated TestPlan into the source of a Playwright spec file.
 *
 * Pure: takes a plan, returns a string and a set of counts. No filesystem, no
 * network, so the interesting logic is testable without touching either.
 *
 * @param {object} plan - a plan that has been through parseTestPlan()
 * @param {object} [options]
 * @param {object} [options.locators] - parsed locator map, pinning names to test ids
 * @returns {{source: string, stats: object}}
 */
export function generateSpec(plan, { locators = null } = {}) {
  const mode = specMode(plan);
  const stats = {
    tests: 0,
    runnable: 0,
    fixme: 0,
    steps: 0,
    translatedSteps: 0,
    assertions: 0,
    // Per-case detail, so a coverage report can say which cases are automated
    // rather than only how many.
    cases: [],
  };

  const blocks = [];
  for (const category of CATEGORIES) {
    const cases = plan.testCases.filter((testCase) => testCase.category === category);
    if (cases.length === 0) continue;

    const body = cases.map((testCase) => renderTestCase(testCase, stats, mode)).join("\n\n");
    blocks.push(`test.describe(${quote(CATEGORY_LABELS[category])}, () => {\n${body}\n});`);
  }

  const preamble = mode === "api" ? API_PREAMBLE : uiPreamble(locators);
  const source = [header(plan), preamble, blocks.join("\n\n"), ""].join("\n");
  return { source, stats, mode };
}

function header(plan) {
  return [
    "// Generated by ai-test-generator. Regenerating overwrites this file.",
    "//",
    `// Source: ${plan.sourceSummary}`,
    `// Generated: ${plan.generatedAt}`,
    "//",
    "// Tests marked test.fixme have steps the generator could not translate into",
    "// Playwright calls. They are skipped rather than passed — fill in the TODOs",
    "// and change fixme to test to bring them into the suite.",
  ].join("\n");
}

/**
 * The UI preamble carries the locator map into the generated file as data.
 *
 * Written as a plain attribute selector rather than Playwright's getByTestId,
 * so the spec does not depend on a testIdAttribute setting in someone's
 * config to keep working.
 */
export function uiPreamble(locators) {
  const hasMap = locators && Object.keys(locators.elements).length > 0;
  const attribute = locators?.attribute ?? DEFAULT_TEST_ID_ATTRIBUTE;

  const mapBlock = hasMap
    ? `
// Names used in the plan, pinned to this app's test ids.
const TEST_ID_ATTRIBUTE = '${attribute}';
const LOCATORS = ${JSON.stringify(locators.elements, null, 2)};

const byTestId = (page, name) =>
  page.locator(\`[\${TEST_ID_ATTRIBUTE}="\${LOCATORS[name]}"]\`);
`
    : "";

  const fieldBody = hasMap
    ? `  LOCATORS[name]
    ? byTestId(page, name)
    : page.getByLabel(name).or(page.getByPlaceholder(name)).first();`
    : `  page.getByLabel(name).or(page.getByPlaceholder(name)).first();`;

  const byRoleBody = hasMap
    ? `  LOCATORS[name] ? byTestId(page, name) : page.getByRole(role, { name });`
    : `  page.getByRole(role, { name });`;

  const clickableBody = hasMap
    ? `  LOCATORS[name]
    ? byTestId(page, name)
    : page.getByRole('button', { name }).or(page.getByRole('link', { name })).first();`
    : `  page.getByRole('button', { name }).or(page.getByRole('link', { name })).first();`;

  return `
import { test, expect } from '@playwright/test';
${mapBlock}
/** Matches a form control by test id when one is mapped, else by label or placeholder. */
const field = (page, name) =>
${fieldBody}

/** Matches a button or link by test id when one is mapped, else by accessible name. */
const clickable = (page, name) =>
${clickableBody}

/** Matches by role, unless the plan name is pinned to a test id. */
const byRole = (page, role, name) =>
${byRoleBody}
`;
}

// API specs need no locator helpers — the request fixture is the whole surface.
const API_PREAMBLE = `
import { test, expect } from '@playwright/test';
`;


function renderTestCase(testCase, stats, mode) {
  const lines = [];
  const unresolved = [];
  let assertions = 0;

  for (const precondition of testCase.preconditions) {
    lines.push(`${INDENT.repeat(2)}// Given: ${precondition}`);
  }
  if (testCase.preconditions.length > 0) lines.push("");

  testCase.steps.forEach((step, index) => {
    stats.steps += 1;
    lines.push(`${INDENT.repeat(2)}// ${index + 1}. ${step.action}`);

    const action = translateAction(step.action, mode);
    if (action.resolved) {
      stats.translatedSteps += 1;
      lines.push(...indent(action.statements, 2));
    } else {
      unresolved.push(`step ${index + 1}: ${step.action}`);
      lines.push(`${INDENT.repeat(2)}// TODO: translate this step`);
    }

    const observation = translateObservation(step.expectedObservation, mode);
    if (observation.statements.length > 0) {
      assertions += observation.statements.length;
      lines.push(...indent(observation.statements, 2));
    } else if (!observation.resolved) {
      unresolved.push(`assertion for step ${index + 1}: ${step.expectedObservation}`);
      lines.push(`${INDENT.repeat(2)}// TODO: assert — ${step.expectedObservation}`);
    }

    lines.push("");
  });

  lines.push(`${INDENT.repeat(2)}// Expect: ${testCase.expectedResult}`);
  const outcome = translateObservation(testCase.expectedResult, mode);
  if (outcome.statements.length > 0) {
    assertions += outcome.statements.length;
    lines.push(...indent(outcome.statements, 2));
  } else {
    unresolved.push(`final assertion: ${testCase.expectedResult}`);
    lines.push(`${INDENT.repeat(2)}// TODO: assert the expected result`);
  }

  // A test that asserts nothing passes by doing nothing, which is worse than a
  // test that is openly unfinished. Never emit one as runnable.
  const needsWork = unresolved.length > 0 || assertions === 0;

  stats.tests += 1;
  stats.assertions += assertions;
  if (needsWork) stats.fixme += 1;
  else stats.runnable += 1;

  stats.cases.push({
    id: testCase.id,
    title: testCase.title,
    category: testCase.category,
    priority: testCase.priority,
    automated: !needsWork,
    assertions,
    unresolved: [...unresolved],
  });

  const title = `${testCase.id} · ${testCase.title}`;
  const opener = needsWork ? "test.fixme" : "test";
  const notes = needsWork ? renderNotes(unresolved, assertions) : [];
  const fixture = mode === "api" ? "request" : "page";

  // Every generated request assigns to one binding, declared here so a case
  // can make several calls in sequence.
  const preamble = lines.some((line) => line.includes("response = await request."))
    ? [`${INDENT.repeat(2)}let response;`, ""]
    : [];

  return [
    ...notes,
    `${INDENT}${opener}(${quote(title)}, async ({ ${fixture} }) => {`,
    ...preamble,
    ...lines,
    `${INDENT}});`,
  ].join("\n");
}

function renderNotes(unresolved, assertions) {
  const notes = [`${INDENT}// Needs attention before this test can run:`];
  for (const item of unresolved) {
    notes.push(`${INDENT}//   - ${item}`);
  }
  if (assertions === 0) {
    notes.push(`${INDENT}//   - nothing in this case could be turned into an assertion`);
  }
  return notes;
}

function indent(statements, depth) {
  return statements.map((statement) => `${INDENT.repeat(depth)}${statement}`);
}

/** Filename-safe slug derived from a plan's summary. */
export function slugify(value, fallback = "test-plan") {
  const slug = String(value)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .split("-")
    .slice(0, 6)
    .join("-");
  return slug || fallback;
}

/** One-line summary of a codegen run, for the CLI to print. */
export function summarizeStats(stats) {
  const stepPercent =
    stats.steps === 0 ? 0 : Math.round((stats.translatedSteps / stats.steps) * 100);
  return (
    `${stats.tests} tests · ${stats.runnable} runnable · ${stats.fixme} need work · ` +
    `${stats.translatedSteps}/${stats.steps} steps translated (${stepPercent}%) · ` +
    `${stats.assertions} assertions`
  );
}
